#
# dirtpan/Makefile - Quick and dirty IPv4 over 802.15.4 tunnel
#
# Written 2011 by Werner Almesberger
# Copyright 2011 Werner Almesberger
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#


MAIN = dirtpan

include ../Makefile.common

CFLAGS += -I. -I../../install/lowpan-tools-0.2.2/include/ \
	  -I../../install/linux-zigbee/include/
