#!/bin/sh

. ./Common


gpio_ben()
{
	step "GPIO scan"
	todo
}


xtal_ben()
{
	step "Crystal frequency"
	cmd "$LOCAL_EXEC atrf-xtal -d $LOCAL_DUT -b \\\`cat $CLKREF\\\` -p 50 100"
	expect_re ppm	# we catch any problems via the exit code
}


begin ben.profile ben.xtal
# power ?
gpio_ben
identify
xtal_ben
spectrum
transmit
