#!/bin/sh

. ./Common


gpio_ben()
{
	step "GPIO scan"
	todo
}


xtal_ben()
{
	step "Crystal frequency"
	cmd "$LOCAL_EXEC atrf-xtal -d $LOCAL_DUT 100"
	expect_re '4350[012]\.'	# @@@ very crude ...
}


begin ben.profile
# power ?
gpio_ben
identify
xtal_ben
spectrum
transmit
