#!/bin/sh

. ./Common


USB_ID=20b7:1540
CLOCK_DRIFT_PPM=50


enumerate()
{
	step "Enumeration"
	cmd "usbwait -t 5 $USB_ID && echo okay"
	expect okay
}


led()
{
	step "LED"
	todo
}


gpio_usb()
{
	step "GPIO scan"
	todo
}


xtal_usb()
{
	step "Crystal frequency"
	cmd "$LOCAL_EXEC atrf-xtal -d $LOCAL_DUT -p $CLOCK_DRIFT_PPM"
	expect_re ppm   # we catch any problems via the exit code
}


begin usb.profile
enumerate
led
# power ?
gpio_usb
identify
xtal_usb
spectrum
transmit
