#!/bin/sh

. ./Common


enumerate()
{
	step "Enumeration"
	cmd "usbwait -t 5 20b7:1540 && echo okay"
	expect okay
}


led()
{
	step "LED"
	todo
}


gpio_usb()
{
	step "GPIO scan"
	todo
}


xtal_usb()
{
	step "Crystal frequency"
	todo
}


begin usb.profile
enumerate
led
# power ?
gpio_usb
identify
xtal_usb
spectrum
transmit
