#!/bin/sh
if [ -z "$1" ]; then
    echo "usage: $0 file" 1>&2
    exit 1
fi
if [ ! -f "$1" ]; then
    echo "$1: not found" 1>&2
    exit 1
fi
gnuplot -persist <<EOF
set xlabel "MHz"
set ylabel "dB"
set yrange [-30:-20]
plot "<sed '\$d' $1" using (\$1):(log(\$3)/log(10)*10) with lines notitle
EOF
