#!/bin/sh -e
DIR=/home/moko/svn.openmoko.org/developers/werner/cncmap
RECT=$DIR/rect/rect
ALIGN=$DIR/align/align
ZMAP=$DIR/zmap/zmap
GP2RML=$DIR/gp2rml/gp2rml
CAMEO=../../../cae-tools/cameo/cameo

GEN=${1:-./pcb.pl}

rdata="19.6 13.0 -56.2  19.6 53.1 -56.1  110.7 14.1 -56.2"
rdate="15.9 13.1 -57.2  15.9 77.4 -57.1  120.8 15.1 -57.0"
rdate="17.2  9.5 -57.0  21.5 76.2 -57.1  126.8  9.0 -56.9"
rdata="8.1 11.2 -56.3  8.1 80.1 -56.1  117.2 12.8 -55.9"
# lower Z by 0.3 mm relative to average (-56.1)
Z=-56.6

rect=`$RECT $rdata | awk '{$3 = ""; print}'`

$GEN |
  awk '{ if ($3 != "") $3 += '$Z'; print $0; }' |
  $CAMEO -d 0.4445 |
  $ALIGN 0 1 $rect |
	# angle, reference (lower left corner), rect
  $GP2RML 2 0.5 0.5
	# clearance, xy speed, z speed
# since everything is in the same plane, z clearance must be thickness plus
# real clearance !
