#!/bin/sh
PATH=$PATH:/home/qi/cae-tools/cameo
PATH=$PATH:/home/moko/svn.openmoko.org/developers/werner/cncmap/gp2rml

cameo <<EOF
mm

gerber 35mil ../atusb-PCB_Edges.gbr
align 1 8.1mm 11.2mm	# align relative to board corner
translate 25mm 2mm	# move to PCB zone assigned to project
translate 2mm 17mm	# move a bit further
array 19mm 36mm 1 0	# skip over previous boards
z 0 -56.1mm		# board surface
z -0.8mm		# board thickness
z -0.5mm		# tool extra depth
offset
write mill.gp
clear

excellon ../atusb.drl
drill 7mil 15mil	# 12.5-13.5 mil drill
write drill.gp

remainder
mill 35mil 0.01mm	# 35 mil endmill
append mill.gp

remainder
empty
EOF


gp2rml 2 0.5 0.5 mill.gp >mill.rml
gp2rml 2 0.1 0.5 drill.gp >drill.rml


cat <<EOF >Makefile
SPOOL=/home/moko/svn.openmoko.org/developers/werner/cncmap/spool/spool
CNGT=/home/qi/cae-tools/cngt/cngt

.PHONY:		mill drill cng

mill:
		PORT=/dev/ttyUSB0 \$(SPOOL) mill.rml

drill:
		PORT=/dev/ttyUSB0 \$(SPOOL) drill.rml

cng:
		\$(CNGT) -56.1 20 50 39
EOF
