#
# atusb-eui64/Makefile - Build the ATUSB EUI64 EEPROM writing and readin utility
#
# Written 2015 by Stefan Schmidt
# Copyright 2015 Stefan Schmidt
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#


MAIN = atusb-eui64

include ../Makefile.common
